// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYX6tQqX_YOUR_WEB_API_KEY',
    appId: '1:1034897796412:web:YOUR_WEB_APP_ID',
    messagingSenderId: '1034897796412',
    projectId: 'focusorelse-5151a',
    authDomain: 'focusorelse-5151a.firebaseapp.com',
    storageBucket: 'focusorelse-5151a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8GrsRfqNFNcEZLDfPc0A6ZvHxmdaNU_E',
    appId: '1:1034897796412:android:8e043bc8b58b8a4d874239',
    messagingSenderId: '1034897796412',
    projectId: 'focusorelse-5151a',
    storageBucket: 'focusorelse-5151a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XQWmt9zOugn7mM_WgGrBEe75o60pIMI',
    appId: '1:1034897796412:ios:dc1fdaaa82c5fa28874239',
    messagingSenderId: '1034897796412',
    projectId: 'focusorelse-5151a',
    storageBucket: 'focusorelse-5151a.firebasestorage.app',
    iosBundleId: 'com.example.focusorelse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2XQWmt9zOugn7mM_WgGrBEe75o60pIMI',
    appId: '1:1034897796412:ios:dc1fdaaa82c5fa28874239',
    messagingSenderId: '1034897796412',
    projectId: 'focusorelse-5151a',
    storageBucket: 'focusorelse-5151a.firebasestorage.app',
    iosBundleId: 'com.example.focusorelse',
  );
}
